name: "app"
only-arches: [ i386 ]
buildsystem: simple
build-commands:
  - "mkdir -p /app/share/DefleMask"
  - "cp -R * /app/share/DefleMask"
sources:
  - type: archive
    url: http://deflemask.com/DefleMask_Linux.tar.gz
    sha256: "7c92b81843345d5c4f239d5deebc264f02556a98f7c4272523978bb963a6feee"
    strip-components: 0

